services:
  - docker

language: scala
scala: 2.11.7
jdk: oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true -DjavaVersion=1.8
script: mvn install

after_success:
  - ./deploy.sh
